# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qb4WkVZYhH_312mLp6xz97RZSTdmuUrA
"""

import pandas as pd
import matplotlib.pyplot as plt

# Leer el archivo CSV
file_path = 'df2_cleaned_updated.csv'  # Cambia esto por la ruta correcta de tu archivo
df = pd.read_csv(file_path)

# Reemplazar los valores en la columna 'Default_Prestamo': 1 = 'PagoPrestamo', 0 = 'No_PagoPrestamo'
df['Default_Prestamo'] = df['Default_Prestamo'].replace({1: 'PagoPrestamo', 0: 'No_PagoPrestamo'})

# Contar la cantidad de cada tipo en la columna 'Default_Prestamo'
default_counts = df['Default_Prestamo'].value_counts()

# Generar el gráfico de barras
plt.figure(figsize=(8, 6))
bars = default_counts.plot(kind='bar', color=['blue', 'orange'])
plt.title('Cantidad de PagoPrestamo y No_PagoPrestamo')
plt.xlabel('Tipo de Prestamo')
plt.ylabel('Cantidad')
plt.xticks(rotation=0)

# Agregar las cantidades encima de las barras
for i, count in enumerate(default_counts):
    plt.text(i, count + 50, str(count), ha='center', fontsize=12)

# Mostrar el gráfico
plt.show()

# Filtrar los datos de aquellos que no pagaron el préstamo
no_pago_prestamo = df[df['Default_Prestamo'] == 'No_PagoPrestamo']

# Generar un gráfico de caja (boxplot) para ver la distribución de las edades de los que no pagaron el préstamo
plt.figure(figsize=(8, 6))
plt.boxplot(no_pago_prestamo['Edad'], vert=False, patch_artist=True, boxprops=dict(facecolor='lightblue'))
plt.title('Distribución de Edad - No_PagoPrestamo (Boxplot)')
plt.xlabel('Edad')

# Mostrar el gráfico
plt.show()
